/home/vazumah/Python_Projects/Li_NRR/autocad_start/bulk_relaxations
# conda environments:
#
                         /home/vazumah/Python_Projects/Environments/hpc_homeworks
base                  *  /home/vazumah/anaconda3
GPAW                     /home/vazumah/anaconda3/envs/GPAW
NAME                     /home/vazumah/anaconda3/envs/NAME
NSMQ                     /home/vazumah/anaconda3/envs/NSMQ
                         /home/vazumah/miniconda3

rank=24 L00: Traceback (most recent call last):
rank=24 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=24 L02:     sys.exit(main())
rank=24 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=24 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=24 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=24 L06:     f(args)
rank=24 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=24 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=24 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=24 L10:     return _run_module_code(code, init_globals, run_name,
rank=24 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=24 L12:     _run_code(code, mod_globals, init_globals,
rank=24 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=24 L14:     exec(code, run_globals)
rank=24 L15:   File "g2_metals.py", line 70, in <module>
rank=24 L16:     relax(slab)
rank=24 L17:   File "g2_metals.py", line 68, in relax
rank=24 L18:     dyn.run(fmax=fmax)
rank=24 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=24 L20:     return Dynamics.run(self)
rank=24 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=24 L22:     for converged in Dynamics.irun(self):
rank=24 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=24 L24:     self.atoms.get_forces()
rank=27 L00: Traceback (most recent call last):
rank=27 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=27 L02:     sys.exit(main())
rank=27 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=27 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=27 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=27 L06:     f(args)
rank=27 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=27 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=27 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=27 L10:     return _run_module_code(code, init_globals, run_name,
rank=27 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=27 L12:     _run_code(code, mod_globals, init_globals,
rank=27 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=27 L14:     exec(code, run_globals)
rank=27 L15:   File "g2_metals.py", line 70, in <module>
rank=27 L16:     relax(slab)
rank=31 L00: Traceback (most recent call last):
rank=31 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=31 L02:     sys.exit(main())
rank=31 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=31 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=31 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=31 L06:     f(args)
rank=31 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=31 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=31 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=31 L10:     return _run_module_code(code, init_globals, run_name,
rank=31 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=31 L12:     _run_code(code, mod_globals, init_globals,
rank=31 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=31 L14:     exec(code, run_globals)
rank=31 L15:   File "g2_metals.py", line 70, in <module>
rank=31 L16:     relax(slab)
rank=31 L17:   File "g2_metals.py", line 68, in relax
rank=31 L18:     dyn.run(fmax=fmax)
rank=31 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=31 L20:     return Dynamics.run(self)
rank=31 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=31 L22:     for converged in Dynamics.irun(self):
rank=31 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=31 L24:     self.atoms.get_forces()
rank=31 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=31 L26:     forces = self._calc.get_forces(self)
rank=31 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=31 L28:     return self.get_property('forces', atoms)
rank=31 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=31 L30:     self.calculate(atoms, [name], system_changes)
rank=31 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=31 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=31 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=31 L34:     self.initialize(atoms)
rank=31 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=31 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=01 L00: Traceback (most recent call last):
rank=01 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=01 L02:     sys.exit(main())
rank=01 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=01 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=01 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=01 L06:     f(args)
rank=01 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=01 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=01 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=01 L10:     return _run_module_code(code, init_globals, run_name,
rank=01 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=01 L12:     _run_code(code, mod_globals, init_globals,
rank=01 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=01 L14:     exec(code, run_globals)
rank=01 L15:   File "g2_metals.py", line 70, in <module>
rank=02 L00: Traceback (most recent call last):
rank=02 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=02 L02:     sys.exit(main())
rank=02 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=02 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=02 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=02 L06:     f(args)
rank=02 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=02 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=02 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=02 L10:     return _run_module_code(code, init_globals, run_name,
rank=02 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=02 L12:     _run_code(code, mod_globals, init_globals,
rank=02 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=02 L14:     exec(code, run_globals)
rank=02 L15:   File "g2_metals.py", line 70, in <module>
rank=02 L16:     relax(slab)
rank=02 L17:   File "g2_metals.py", line 68, in relax
rank=02 L18:     dyn.run(fmax=fmax)
rank=02 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=02 L20:     return Dynamics.run(self)
rank=02 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=02 L22:     for converged in Dynamics.irun(self):
rank=02 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=02 L24:     self.atoms.get_forces()
rank=02 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=04 L00: Traceback (most recent call last):
rank=04 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=04 L02:     sys.exit(main())
rank=04 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=04 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=04 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=04 L06:     f(args)
rank=04 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=04 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=04 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=04 L10:     return _run_module_code(code, init_globals, run_name,
rank=04 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=04 L12:     _run_code(code, mod_globals, init_globals,
rank=04 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=04 L14:     exec(code, run_globals)
rank=04 L15:   File "g2_metals.py", line 70, in <module>
rank=04 L16:     relax(slab)
rank=04 L17:   File "g2_metals.py", line 68, in relax
rank=04 L18:     dyn.run(fmax=fmax)
rank=04 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=04 L20:     return Dynamics.run(self)
rank=04 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=04 L22:     for converged in Dynamics.irun(self):
rank=05 L00: Traceback (most recent call last):
rank=05 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=05 L02:     sys.exit(main())
rank=05 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=05 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=05 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=05 L06:     f(args)
rank=05 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=05 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=05 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=05 L10:     return _run_module_code(code, init_globals, run_name,
rank=05 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=05 L12:     _run_code(code, mod_globals, init_globals,
rank=05 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=05 L14:     exec(code, run_globals)
rank=05 L15:   File "g2_metals.py", line 70, in <module>
rank=05 L16:     relax(slab)
rank=05 L17:   File "g2_metals.py", line 68, in relax
rank=05 L18:     dyn.run(fmax=fmax)
rank=05 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=05 L20:     return Dynamics.run(self)
rank=05 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=05 L22:     for converged in Dynamics.irun(self):
rank=05 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=05 L24:     self.atoms.get_forces()
rank=06 L00: Traceback (most recent call last):
rank=06 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=06 L02:     sys.exit(main())
rank=06 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=06 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=06 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=06 L06:     f(args)
rank=06 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=06 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=06 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=06 L10:     return _run_module_code(code, init_globals, run_name,
rank=06 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=06 L12:     _run_code(code, mod_globals, init_globals,
rank=06 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=06 L14:     exec(code, run_globals)
rank=06 L15:   File "g2_metals.py", line 70, in <module>
rank=06 L16:     relax(slab)
rank=06 L17:   File "g2_metals.py", line 68, in relax
rank=06 L18:     dyn.run(fmax=fmax)
rank=06 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=06 L20:     return Dynamics.run(self)
rank=06 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=06 L22:     for converged in Dynamics.irun(self):
rank=06 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=06 L24:     self.atoms.get_forces()
rank=06 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=07 L00: Traceback (most recent call last):
rank=07 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=07 L02:     sys.exit(main())
rank=07 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=07 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=07 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=07 L06:     f(args)
rank=07 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=07 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=07 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=07 L10:     return _run_module_code(code, init_globals, run_name,
rank=07 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=07 L12:     _run_code(code, mod_globals, init_globals,
rank=07 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=07 L14:     exec(code, run_globals)
rank=07 L15:   File "g2_metals.py", line 70, in <module>
rank=07 L16:     relax(slab)
rank=07 L17:   File "g2_metals.py", line 68, in relax
rank=07 L18:     dyn.run(fmax=fmax)
rank=07 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=08 L00: Traceback (most recent call last):
rank=08 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=08 L02:     sys.exit(main())
rank=08 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=08 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=08 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=08 L06:     f(args)
rank=08 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=08 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=08 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=08 L10:     return _run_module_code(code, init_globals, run_name,
rank=08 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=08 L12:     _run_code(code, mod_globals, init_globals,
rank=08 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=08 L14:     exec(code, run_globals)
rank=08 L15:   File "g2_metals.py", line 70, in <module>
rank=08 L16:     relax(slab)
rank=08 L17:   File "g2_metals.py", line 68, in relax
rank=08 L18:     dyn.run(fmax=fmax)
rank=08 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=08 L20:     return Dynamics.run(self)
rank=08 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=08 L22:     for converged in Dynamics.irun(self):
rank=08 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=08 L24:     self.atoms.get_forces()
rank=08 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=08 L26:     forces = self._calc.get_forces(self)
rank=08 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=08 L28:     return self.get_property('forces', atoms)
rank=08 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=08 L30:     self.calculate(atoms, [name], system_changes)
rank=08 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=08 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=08 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=08 L34:     self.initialize(atoms)
rank=08 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=08 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=09 L00: Traceback (most recent call last):
rank=09 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=09 L02:     sys.exit(main())
rank=09 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=09 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=09 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=09 L06:     f(args)
rank=09 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=09 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=09 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=09 L10:     return _run_module_code(code, init_globals, run_name,
rank=09 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=09 L12:     _run_code(code, mod_globals, init_globals,
rank=09 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=09 L14:     exec(code, run_globals)
rank=09 L15:   File "g2_metals.py", line 70, in <module>
rank=09 L16:     relax(slab)
rank=09 L17:   File "g2_metals.py", line 68, in relax
rank=09 L18:     dyn.run(fmax=fmax)
rank=09 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=09 L20:     return Dynamics.run(self)
rank=09 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=09 L22:     for converged in Dynamics.irun(self):
rank=09 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=09 L24:     self.atoms.get_forces()
rank=09 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=09 L26:     forces = self._calc.get_forces(self)
rank=09 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=09 L28:     return self.get_property('forces', atoms)
rank=09 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=10 L00: Traceback (most recent call last):
rank=10 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=10 L02:     sys.exit(main())
rank=10 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=10 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=10 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=10 L06:     f(args)
rank=10 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=10 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=10 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=10 L10:     return _run_module_code(code, init_globals, run_name,
rank=10 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=10 L12:     _run_code(code, mod_globals, init_globals,
rank=10 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=10 L14:     exec(code, run_globals)
rank=10 L15:   File "g2_metals.py", line 70, in <module>
rank=10 L16:     relax(slab)
rank=10 L17:   File "g2_metals.py", line 68, in relax
rank=10 L18:     dyn.run(fmax=fmax)
rank=10 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=10 L20:     return Dynamics.run(self)
rank=10 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=10 L22:     for converged in Dynamics.irun(self):
rank=10 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=10 L24:     self.atoms.get_forces()
rank=10 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=10 L26:     forces = self._calc.get_forces(self)
rank=10 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=12 L00: Traceback (most recent call last):
rank=12 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=12 L02:     sys.exit(main())
rank=12 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=12 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=12 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=12 L06:     f(args)
rank=12 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=12 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=12 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=12 L10:     return _run_module_code(code, init_globals, run_name,
rank=12 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=12 L12:     _run_code(code, mod_globals, init_globals,
rank=12 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=12 L14:     exec(code, run_globals)
rank=12 L15:   File "g2_metals.py", line 70, in <module>
rank=12 L16:     relax(slab)
rank=12 L17:   File "g2_metals.py", line 68, in relax
rank=12 L18:     dyn.run(fmax=fmax)
rank=12 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=12 L20:     return Dynamics.run(self)
rank=12 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=12 L22:     for converged in Dynamics.irun(self):
rank=12 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=12 L24:     self.atoms.get_forces()
rank=12 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=12 L26:     forces = self._calc.get_forces(self)
rank=12 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=12 L28:     return self.get_property('forces', atoms)
rank=12 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=12 L30:     self.calculate(atoms, [name], system_changes)
rank=12 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=12 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=12 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=12 L34:     self.initialize(atoms)
rank=13 L00: Traceback (most recent call last):
rank=13 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=13 L02:     sys.exit(main())
rank=13 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=13 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=13 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=13 L06:     f(args)
rank=13 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=13 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=13 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=13 L10:     return _run_module_code(code, init_globals, run_name,
rank=13 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=13 L12:     _run_code(code, mod_globals, init_globals,
rank=13 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=13 L14:     exec(code, run_globals)
rank=13 L15:   File "g2_metals.py", line 70, in <module>
rank=13 L16:     relax(slab)
rank=13 L17:   File "g2_metals.py", line 68, in relax
rank=13 L18:     dyn.run(fmax=fmax)
rank=13 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=13 L20:     return Dynamics.run(self)
rank=13 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=13 L22:     for converged in Dynamics.irun(self):
rank=13 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=13 L24:     self.atoms.get_forces()
rank=13 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=13 L26:     forces = self._calc.get_forces(self)
rank=13 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=13 L28:     return self.get_property('forces', atoms)
rank=13 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=13 L30:     self.calculate(atoms, [name], system_changes)
rank=13 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=13 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=13 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=13 L34:     self.initialize(atoms)
rank=13 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=13 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=13 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=13 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=13 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=13 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=13 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=13 L42:     self.check_direction(gd, gd.pbc_c)
rank=14 L00: Traceback (most recent call last):
rank=14 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=14 L02:     sys.exit(main())
rank=14 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=14 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=14 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=14 L06:     f(args)
rank=14 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=14 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=14 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=14 L10:     return _run_module_code(code, init_globals, run_name,
rank=14 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=14 L12:     _run_code(code, mod_globals, init_globals,
rank=14 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=14 L14:     exec(code, run_globals)
rank=14 L15:   File "g2_metals.py", line 70, in <module>
rank=14 L16:     relax(slab)
rank=14 L17:   File "g2_metals.py", line 68, in relax
rank=14 L18:     dyn.run(fmax=fmax)
rank=14 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=14 L20:     return Dynamics.run(self)
rank=14 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=14 L22:     for converged in Dynamics.irun(self):
rank=14 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=14 L24:     self.atoms.get_forces()
rank=14 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=14 L26:     forces = self._calc.get_forces(self)
rank=14 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=14 L28:     return self.get_property('forces', atoms)
rank=14 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=14 L30:     self.calculate(atoms, [name], system_changes)
rank=14 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=14 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=14 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=14 L34:     self.initialize(atoms)
rank=14 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=14 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=14 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=14 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=14 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=14 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=14 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=14 L42:     self.check_direction(gd, gd.pbc_c)
rank=14 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=15 L00: Traceback (most recent call last):
rank=15 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=15 L02:     sys.exit(main())
rank=15 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=15 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=15 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=15 L06:     f(args)
rank=15 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=15 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=15 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=15 L10:     return _run_module_code(code, init_globals, run_name,
rank=15 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=15 L12:     _run_code(code, mod_globals, init_globals,
rank=15 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=15 L14:     exec(code, run_globals)
rank=15 L15:   File "g2_metals.py", line 70, in <module>
rank=15 L16:     relax(slab)
rank=15 L17:   File "g2_metals.py", line 68, in relax
rank=15 L18:     dyn.run(fmax=fmax)
rank=15 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=15 L20:     return Dynamics.run(self)
rank=15 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=15 L22:     for converged in Dynamics.irun(self):
rank=15 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=15 L24:     self.atoms.get_forces()
rank=15 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=15 L26:     forces = self._calc.get_forces(self)
rank=15 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=15 L28:     return self.get_property('forces', atoms)
rank=15 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=15 L30:     self.calculate(atoms, [name], system_changes)
rank=15 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=15 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=15 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=15 L34:     self.initialize(atoms)
rank=15 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=15 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=15 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=16 L00: Traceback (most recent call last):
rank=16 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=16 L02:     sys.exit(main())
rank=16 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=16 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=16 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=16 L06:     f(args)
rank=16 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=16 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=16 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=16 L10:     return _run_module_code(code, init_globals, run_name,
rank=16 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=16 L12:     _run_code(code, mod_globals, init_globals,
rank=16 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=16 L14:     exec(code, run_globals)
rank=16 L15:   File "g2_metals.py", line 70, in <module>
rank=16 L16:     relax(slab)
rank=16 L17:   File "g2_metals.py", line 68, in relax
rank=16 L18:     dyn.run(fmax=fmax)
rank=16 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=16 L20:     return Dynamics.run(self)
rank=16 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=16 L22:     for converged in Dynamics.irun(self):
rank=16 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=16 L24:     self.atoms.get_forces()
rank=16 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=16 L26:     forces = self._calc.get_forces(self)
rank=16 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=16 L28:     return self.get_property('forces', atoms)
rank=16 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=16 L30:     self.calculate(atoms, [name], system_changes)
rank=18 L00: Traceback (most recent call last):
rank=18 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=18 L02:     sys.exit(main())
rank=18 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=18 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=18 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=18 L06:     f(args)
rank=18 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=18 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=18 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=18 L10:     return _run_module_code(code, init_globals, run_name,
rank=18 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=18 L12:     _run_code(code, mod_globals, init_globals,
rank=18 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=18 L14:     exec(code, run_globals)
rank=18 L15:   File "g2_metals.py", line 70, in <module>
rank=18 L16:     relax(slab)
rank=18 L17:   File "g2_metals.py", line 68, in relax
rank=18 L18:     dyn.run(fmax=fmax)
rank=18 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=18 L20:     return Dynamics.run(self)
rank=18 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=18 L22:     for converged in Dynamics.irun(self):
rank=18 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=18 L24:     self.atoms.get_forces()
rank=18 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=18 L26:     forces = self._calc.get_forces(self)
rank=18 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=18 L28:     return self.get_property('forces', atoms)
rank=18 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=18 L30:     self.calculate(atoms, [name], system_changes)
rank=18 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=18 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=18 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=18 L34:     self.initialize(atoms)
rank=18 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=18 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=18 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=18 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=18 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=18 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=20 L00: Traceback (most recent call last):
rank=20 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=20 L02:     sys.exit(main())
rank=20 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=20 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=20 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=20 L06:     f(args)
rank=20 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=20 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=20 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=20 L10:     return _run_module_code(code, init_globals, run_name,
rank=20 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=20 L12:     _run_code(code, mod_globals, init_globals,
rank=20 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=20 L14:     exec(code, run_globals)
rank=20 L15:   File "g2_metals.py", line 70, in <module>
rank=20 L16:     relax(slab)
rank=20 L17:   File "g2_metals.py", line 68, in relax
rank=20 L18:     dyn.run(fmax=fmax)
rank=20 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=20 L20:     return Dynamics.run(self)
rank=20 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=20 L22:     for converged in Dynamics.irun(self):
rank=20 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=20 L24:     self.atoms.get_forces()
rank=20 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=20 L26:     forces = self._calc.get_forces(self)
rank=20 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=20 L28:     return self.get_property('forces', atoms)
rank=20 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=20 L30:     self.calculate(atoms, [name], system_changes)
rank=20 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=20 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=20 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=20 L34:     self.initialize(atoms)
rank=20 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=20 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=20 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=20 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=20 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=20 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=21 L00: Traceback (most recent call last):
rank=21 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=21 L02:     sys.exit(main())
rank=21 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=21 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=21 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=21 L06:     f(args)
rank=21 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=21 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=21 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=21 L10:     return _run_module_code(code, init_globals, run_name,
rank=21 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=21 L12:     _run_code(code, mod_globals, init_globals,
rank=21 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=21 L14:     exec(code, run_globals)
rank=21 L15:   File "g2_metals.py", line 70, in <module>
rank=21 L16:     relax(slab)
rank=21 L17:   File "g2_metals.py", line 68, in relax
rank=21 L18:     dyn.run(fmax=fmax)
rank=21 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=21 L20:     return Dynamics.run(self)
rank=21 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=21 L22:     for converged in Dynamics.irun(self):
rank=21 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=21 L24:     self.atoms.get_forces()
rank=21 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=21 L26:     forces = self._calc.get_forces(self)
rank=21 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=21 L28:     return self.get_property('forces', atoms)
rank=21 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=21 L30:     self.calculate(atoms, [name], system_changes)
rank=21 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=21 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=21 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=21 L34:     self.initialize(atoms)
rank=21 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=21 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=21 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=21 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=21 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=21 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=21 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=21 L42:     self.check_direction(gd, gd.pbc_c)
rank=21 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=21 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=22 L00: Traceback (most recent call last):
rank=22 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=22 L02:     sys.exit(main())
rank=22 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=22 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=22 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=22 L06:     f(args)
rank=22 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=22 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=22 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=22 L10:     return _run_module_code(code, init_globals, run_name,
rank=22 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=22 L12:     _run_code(code, mod_globals, init_globals,
rank=22 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=22 L14:     exec(code, run_globals)
rank=22 L15:   File "g2_metals.py", line 70, in <module>
rank=22 L16:     relax(slab)
rank=22 L17:   File "g2_metals.py", line 68, in relax
rank=22 L18:     dyn.run(fmax=fmax)
rank=22 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=22 L20:     return Dynamics.run(self)
rank=22 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=22 L22:     for converged in Dynamics.irun(self):
rank=22 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=22 L24:     self.atoms.get_forces()
rank=22 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=22 L26:     forces = self._calc.get_forces(self)
rank=22 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=22 L28:     return self.get_property('forces', atoms)
rank=22 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=22 L30:     self.calculate(atoms, [name], system_changes)
rank=22 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=22 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=22 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=22 L34:     self.initialize(atoms)
rank=22 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=22 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=22 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=22 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=22 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=22 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=22 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=22 L42:     self.check_direction(gd, gd.pbc_c)
rank=22 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=22 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=22 L45: ValueError: No axis perpendicular to xy-plane!
rank=23 L00: Traceback (most recent call last):
rank=23 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=23 L02:     sys.exit(main())
rank=23 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=23 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=23 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=23 L06:     f(args)
rank=23 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=23 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=23 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=23 L10:     return _run_module_code(code, init_globals, run_name,
rank=23 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=23 L12:     _run_code(code, mod_globals, init_globals,
rank=23 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=23 L14:     exec(code, run_globals)
rank=23 L15:   File "g2_metals.py", line 70, in <module>
rank=23 L16:     relax(slab)
rank=23 L17:   File "g2_metals.py", line 68, in relax
rank=23 L18:     dyn.run(fmax=fmax)
rank=23 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=23 L20:     return Dynamics.run(self)
rank=23 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=23 L22:     for converged in Dynamics.irun(self):
rank=23 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=23 L24:     self.atoms.get_forces()
rank=23 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=23 L26:     forces = self._calc.get_forces(self)
rank=23 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=23 L28:     return self.get_property('forces', atoms)
rank=23 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=23 L30:     self.calculate(atoms, [name], system_changes)
rank=23 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=23 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=23 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=23 L34:     self.initialize(atoms)
rank=27 L17:   File "g2_metals.py", line 68, in relax
rank=27 L18:     dyn.run(fmax=fmax)
rank=27 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=27 L20:     return Dynamics.run(self)
rank=27 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=27 L22:     for converged in Dynamics.irun(self):
rank=27 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=27 L24:     self.atoms.get_forces()
rank=27 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=27 L26:     forces = self._calc.get_forces(self)
rank=27 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=27 L28:     return self.get_property('forces', atoms)
rank=27 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=27 L30:     self.calculate(atoms, [name], system_changes)
rank=27 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=27 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=27 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=27 L34:     self.initialize(atoms)
rank=27 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=27 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=27 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=27 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=27 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=27 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=27 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=27 L42:     self.check_direction(gd, gd.pbc_c)
rank=27 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=27 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=27 L45: ValueError: No axis perpendicular to xy-plane!
rank=25 L00: Traceback (most recent call last):
rank=25 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=25 L02:     sys.exit(main())
rank=25 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=25 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=25 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=25 L06:     f(args)
rank=25 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=25 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=25 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=25 L10:     return _run_module_code(code, init_globals, run_name,
rank=25 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=25 L12:     _run_code(code, mod_globals, init_globals,
rank=25 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=25 L14:     exec(code, run_globals)
rank=25 L15:   File "g2_metals.py", line 70, in <module>
rank=25 L16:     relax(slab)
rank=25 L17:   File "g2_metals.py", line 68, in relax
rank=25 L18:     dyn.run(fmax=fmax)
rank=25 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=25 L20:     return Dynamics.run(self)
rank=25 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=25 L22:     for converged in Dynamics.irun(self):
rank=25 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=25 L24:     self.atoms.get_forces()
rank=25 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=25 L26:     forces = self._calc.get_forces(self)
rank=25 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=25 L28:     return self.get_property('forces', atoms)
rank=25 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=25 L30:     self.calculate(atoms, [name], system_changes)
rank=25 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=25 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=25 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=25 L34:     self.initialize(atoms)
rank=25 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=25 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=25 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=25 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=25 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=25 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=25 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=25 L42:     self.check_direction(gd, gd.pbc_c)
rank=25 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=25 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=25 L45: ValueError: No axis perpendicular to xy-plane!
rank=26 L00: Traceback (most recent call last):
rank=26 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=26 L02:     sys.exit(main())
rank=26 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=26 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=26 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=26 L06:     f(args)
rank=26 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=26 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=26 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=26 L10:     return _run_module_code(code, init_globals, run_name,
rank=26 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=26 L12:     _run_code(code, mod_globals, init_globals,
rank=26 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=26 L14:     exec(code, run_globals)
rank=26 L15:   File "g2_metals.py", line 70, in <module>
rank=26 L16:     relax(slab)
rank=26 L17:   File "g2_metals.py", line 68, in relax
rank=26 L18:     dyn.run(fmax=fmax)
rank=26 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=26 L20:     return Dynamics.run(self)
rank=26 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=26 L22:     for converged in Dynamics.irun(self):
rank=26 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=26 L24:     self.atoms.get_forces()
rank=26 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=26 L26:     forces = self._calc.get_forces(self)
rank=26 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=26 L28:     return self.get_property('forces', atoms)
rank=26 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=26 L30:     self.calculate(atoms, [name], system_changes)
rank=26 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=26 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=26 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=26 L34:     self.initialize(atoms)
rank=26 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=26 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=26 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=26 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=26 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=26 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=26 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=26 L42:     self.check_direction(gd, gd.pbc_c)
rank=26 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=26 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=26 L45: ValueError: No axis perpendicular to xy-plane!
rank=24 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=24 L26:     forces = self._calc.get_forces(self)
rank=24 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=24 L28:     return self.get_property('forces', atoms)
rank=24 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=24 L30:     self.calculate(atoms, [name], system_changes)
rank=24 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=24 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=24 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=24 L34:     self.initialize(atoms)
rank=24 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=24 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=24 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=24 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=24 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=24 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=24 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=24 L42:     self.check_direction(gd, gd.pbc_c)
rank=24 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=24 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=24 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 24): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=28 L00: Traceback (most recent call last):
rank=28 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=28 L02:     sys.exit(main())
rank=28 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=28 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=28 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=28 L06:     f(args)
rank=28 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=28 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=28 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=28 L10:     return _run_module_code(code, init_globals, run_name,
rank=28 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=28 L12:     _run_code(code, mod_globals, init_globals,
rank=28 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=28 L14:     exec(code, run_globals)
rank=28 L15:   File "g2_metals.py", line 70, in <module>
rank=28 L16:     relax(slab)
rank=28 L17:   File "g2_metals.py", line 68, in relax
rank=28 L18:     dyn.run(fmax=fmax)
rank=28 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=28 L20:     return Dynamics.run(self)
rank=28 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=28 L22:     for converged in Dynamics.irun(self):
rank=28 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=28 L24:     self.atoms.get_forces()
rank=28 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=28 L26:     forces = self._calc.get_forces(self)
rank=28 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=28 L28:     return self.get_property('forces', atoms)
rank=28 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=28 L30:     self.calculate(atoms, [name], system_changes)
rank=28 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=28 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=28 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=28 L34:     self.initialize(atoms)
rank=28 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=28 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=28 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=28 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=28 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=28 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=28 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=28 L42:     self.check_direction(gd, gd.pbc_c)
rank=28 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=28 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=28 L45: ValueError: No axis perpendicular to xy-plane!
rank=30 L00: Traceback (most recent call last):
rank=30 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=30 L02:     sys.exit(main())
rank=30 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=30 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=30 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=30 L06:     f(args)
rank=30 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=30 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=30 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=30 L10:     return _run_module_code(code, init_globals, run_name,
rank=30 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=30 L12:     _run_code(code, mod_globals, init_globals,
rank=30 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=30 L14:     exec(code, run_globals)
rank=30 L15:   File "g2_metals.py", line 70, in <module>
rank=30 L16:     relax(slab)
rank=30 L17:   File "g2_metals.py", line 68, in relax
rank=30 L18:     dyn.run(fmax=fmax)
rank=30 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=30 L20:     return Dynamics.run(self)
rank=30 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=30 L22:     for converged in Dynamics.irun(self):
rank=30 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=30 L24:     self.atoms.get_forces()
rank=30 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=30 L26:     forces = self._calc.get_forces(self)
rank=30 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=30 L28:     return self.get_property('forces', atoms)
rank=30 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=30 L30:     self.calculate(atoms, [name], system_changes)
rank=30 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=30 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=30 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=30 L34:     self.initialize(atoms)
rank=30 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=30 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=30 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=30 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=30 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=30 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=30 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=30 L42:     self.check_direction(gd, gd.pbc_c)
rank=30 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=30 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=30 L45: ValueError: No axis perpendicular to xy-plane!
rank=31 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=31 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=31 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=31 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=31 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=31 L42:     self.check_direction(gd, gd.pbc_c)
rank=31 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=31 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=31 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 30): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=01 L16:     relax(slab)
rank=01 L17:   File "g2_metals.py", line 68, in relax
rank=01 L18:     dyn.run(fmax=fmax)
rank=01 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=01 L20:     return Dynamics.run(self)
rank=01 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=01 L22:     for converged in Dynamics.irun(self):
rank=01 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=01 L24:     self.atoms.get_forces()
rank=01 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=01 L26:     forces = self._calc.get_forces(self)
rank=01 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=01 L28:     return self.get_property('forces', atoms)
rank=01 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=01 L30:     self.calculate(atoms, [name], system_changes)
rank=01 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=01 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=01 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=01 L34:     self.initialize(atoms)
rank=01 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=01 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=01 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=01 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=01 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=01 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=01 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=01 L42:     self.check_direction(gd, gd.pbc_c)
rank=01 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=01 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=01 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 1): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=03 L00: Traceback (most recent call last):
rank=03 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=03 L02:     sys.exit(main())
rank=03 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=03 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=03 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=03 L06:     f(args)
rank=03 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=03 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=03 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=03 L10:     return _run_module_code(code, init_globals, run_name,
rank=03 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=03 L12:     _run_code(code, mod_globals, init_globals,
rank=03 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=03 L14:     exec(code, run_globals)
rank=03 L15:   File "g2_metals.py", line 70, in <module>
rank=03 L16:     relax(slab)
rank=03 L17:   File "g2_metals.py", line 68, in relax
rank=03 L18:     dyn.run(fmax=fmax)
rank=03 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=03 L20:     return Dynamics.run(self)
rank=03 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=03 L22:     for converged in Dynamics.irun(self):
rank=03 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=03 L24:     self.atoms.get_forces()
rank=03 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=03 L26:     forces = self._calc.get_forces(self)
rank=03 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=03 L28:     return self.get_property('forces', atoms)
rank=03 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=03 L30:     self.calculate(atoms, [name], system_changes)
rank=03 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=03 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=03 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=03 L34:     self.initialize(atoms)
rank=03 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=03 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=03 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=03 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=03 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=03 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=03 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=03 L42:     self.check_direction(gd, gd.pbc_c)
rank=03 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=03 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=03 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 3): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=02 L26:     forces = self._calc.get_forces(self)
rank=02 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=02 L28:     return self.get_property('forces', atoms)
rank=02 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=02 L30:     self.calculate(atoms, [name], system_changes)
rank=02 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=02 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=02 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=02 L34:     self.initialize(atoms)
rank=02 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=02 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=02 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=02 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=02 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=02 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=02 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=02 L42:     self.check_direction(gd, gd.pbc_c)
rank=02 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=02 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=02 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 2): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=04 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=04 L24:     self.atoms.get_forces()
rank=04 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=04 L26:     forces = self._calc.get_forces(self)
rank=04 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=04 L28:     return self.get_property('forces', atoms)
rank=04 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=04 L30:     self.calculate(atoms, [name], system_changes)
rank=04 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=04 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=04 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=04 L34:     self.initialize(atoms)
rank=04 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=04 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=04 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=04 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=04 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=04 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=04 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=04 L42:     self.check_direction(gd, gd.pbc_c)
rank=04 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=04 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=04 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 4): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=05 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=05 L26:     forces = self._calc.get_forces(self)
rank=05 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=05 L28:     return self.get_property('forces', atoms)
rank=05 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=05 L30:     self.calculate(atoms, [name], system_changes)
rank=05 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=05 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=05 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=05 L34:     self.initialize(atoms)
rank=05 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=05 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=05 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=05 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=05 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=05 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=05 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=05 L42:     self.check_direction(gd, gd.pbc_c)
rank=05 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=05 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=05 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 5): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=06 L26:     forces = self._calc.get_forces(self)
rank=06 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=06 L28:     return self.get_property('forces', atoms)
rank=06 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=06 L30:     self.calculate(atoms, [name], system_changes)
rank=06 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=06 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=06 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=06 L34:     self.initialize(atoms)
rank=06 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=06 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=06 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=06 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=06 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=06 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=06 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=06 L42:     self.check_direction(gd, gd.pbc_c)
rank=06 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=06 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=06 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 6): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=07 L20:     return Dynamics.run(self)
rank=07 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=07 L22:     for converged in Dynamics.irun(self):
rank=07 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=07 L24:     self.atoms.get_forces()
rank=07 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=07 L26:     forces = self._calc.get_forces(self)
rank=07 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=07 L28:     return self.get_property('forces', atoms)
rank=07 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=07 L30:     self.calculate(atoms, [name], system_changes)
rank=07 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=07 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=07 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=07 L34:     self.initialize(atoms)
rank=07 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=07 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=07 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=07 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=07 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=07 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=07 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=07 L42:     self.check_direction(gd, gd.pbc_c)
rank=07 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=07 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=07 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 7): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=08 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=08 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=08 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=08 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=08 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=08 L42:     self.check_direction(gd, gd.pbc_c)
rank=08 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=08 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=08 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 8): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=09 L30:     self.calculate(atoms, [name], system_changes)
rank=09 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=09 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=09 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=09 L34:     self.initialize(atoms)
rank=09 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=09 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=09 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=09 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=09 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=09 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=09 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=09 L42:     self.check_direction(gd, gd.pbc_c)
rank=09 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=09 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=09 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 9): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=11 L00: Traceback (most recent call last):
rank=11 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=11 L02:     sys.exit(main())
rank=11 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=11 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=11 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=11 L06:     f(args)
rank=11 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=11 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=11 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=11 L10:     return _run_module_code(code, init_globals, run_name,
rank=11 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=11 L12:     _run_code(code, mod_globals, init_globals,
rank=11 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=11 L14:     exec(code, run_globals)
rank=11 L15:   File "g2_metals.py", line 70, in <module>
rank=11 L16:     relax(slab)
rank=11 L17:   File "g2_metals.py", line 68, in relax
rank=11 L18:     dyn.run(fmax=fmax)
rank=11 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=11 L20:     return Dynamics.run(self)
rank=11 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=11 L22:     for converged in Dynamics.irun(self):
rank=11 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=11 L24:     self.atoms.get_forces()
rank=11 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=11 L26:     forces = self._calc.get_forces(self)
rank=11 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=11 L28:     return self.get_property('forces', atoms)
rank=11 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=11 L30:     self.calculate(atoms, [name], system_changes)
rank=11 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=11 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=11 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=11 L34:     self.initialize(atoms)
rank=11 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=11 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=11 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=11 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=11 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=11 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=11 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=11 L42:     self.check_direction(gd, gd.pbc_c)
rank=11 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=11 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=11 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 11): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=10 L28:     return self.get_property('forces', atoms)
rank=10 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=10 L30:     self.calculate(atoms, [name], system_changes)
rank=10 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=10 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=10 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=10 L34:     self.initialize(atoms)
rank=10 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=10 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=10 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=10 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=10 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=10 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=10 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=10 L42:     self.check_direction(gd, gd.pbc_c)
rank=10 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=10 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=10 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 10): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=12 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=12 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=12 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=12 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=12 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=12 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=12 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=12 L42:     self.check_direction(gd, gd.pbc_c)
rank=12 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=12 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=12 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 12): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=13 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=13 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=13 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 13): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=14 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=14 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 14): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=15 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=15 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=15 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=15 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=15 L42:     self.check_direction(gd, gd.pbc_c)
rank=15 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=15 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=15 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 15): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=17 L00: Traceback (most recent call last):
rank=17 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=17 L02:     sys.exit(main())
rank=17 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=17 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=17 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=17 L06:     f(args)
rank=17 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=17 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=17 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=17 L10:     return _run_module_code(code, init_globals, run_name,
rank=17 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=17 L12:     _run_code(code, mod_globals, init_globals,
rank=17 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=17 L14:     exec(code, run_globals)
rank=17 L15:   File "g2_metals.py", line 70, in <module>
rank=17 L16:     relax(slab)
rank=17 L17:   File "g2_metals.py", line 68, in relax
rank=17 L18:     dyn.run(fmax=fmax)
rank=17 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=17 L20:     return Dynamics.run(self)
rank=17 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=17 L22:     for converged in Dynamics.irun(self):
rank=17 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=17 L24:     self.atoms.get_forces()
rank=17 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=17 L26:     forces = self._calc.get_forces(self)
rank=17 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=17 L28:     return self.get_property('forces', atoms)
rank=17 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=17 L30:     self.calculate(atoms, [name], system_changes)
rank=17 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=17 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=17 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=17 L34:     self.initialize(atoms)
rank=17 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=17 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=17 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=17 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=17 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=17 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=17 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=17 L42:     self.check_direction(gd, gd.pbc_c)
rank=17 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=17 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=17 L45: ValueError: No axis perpendicular to xy-plane!
rank=16 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=16 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=16 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=16 L34:     self.initialize(atoms)
rank=16 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=16 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=16 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=16 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=16 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=16 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=16 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=16 L42:     self.check_direction(gd, gd.pbc_c)
rank=16 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=16 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=16 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 16): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=19 L00: Traceback (most recent call last):
rank=19 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=19 L02:     sys.exit(main())
rank=19 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=19 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=19 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=19 L06:     f(args)
rank=19 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=19 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=19 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=19 L10:     return _run_module_code(code, init_globals, run_name,
rank=19 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=19 L12:     _run_code(code, mod_globals, init_globals,
rank=19 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=19 L14:     exec(code, run_globals)
rank=19 L15:   File "g2_metals.py", line 70, in <module>
rank=19 L16:     relax(slab)
rank=19 L17:   File "g2_metals.py", line 68, in relax
rank=19 L18:     dyn.run(fmax=fmax)
rank=19 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=19 L20:     return Dynamics.run(self)
rank=19 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=19 L22:     for converged in Dynamics.irun(self):
rank=19 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=19 L24:     self.atoms.get_forces()
rank=19 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=19 L26:     forces = self._calc.get_forces(self)
rank=19 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=19 L28:     return self.get_property('forces', atoms)
rank=19 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=19 L30:     self.calculate(atoms, [name], system_changes)
rank=19 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=19 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=19 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=19 L34:     self.initialize(atoms)
rank=19 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=19 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=19 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=19 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=19 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=19 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=19 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=19 L42:     self.check_direction(gd, gd.pbc_c)
rank=19 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=19 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=19 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 19): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=18 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=18 L42:     self.check_direction(gd, gd.pbc_c)
rank=18 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=18 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=18 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 18): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=20 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=20 L42:     self.check_direction(gd, gd.pbc_c)
rank=20 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=20 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=20 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 20): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=21 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 21): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 22): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=23 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=23 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=23 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=23 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=23 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=23 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=23 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=23 L42:     self.check_direction(gd, gd.pbc_c)
rank=23 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=23 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=23 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 23): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 27): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 25): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 26): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 28): <class 'ValueError'> occurred.  Calling MPI_Abort!
GPAW CLEANUP (node 31): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=00 L00: Traceback (most recent call last):
rank=00 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=00 L02:     sys.exit(main())
rank=00 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=00 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=00 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=00 L06:     f(args)
rank=00 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=00 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=00 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=00 L10:     return _run_module_code(code, init_globals, run_name,
rank=00 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=00 L12:     _run_code(code, mod_globals, init_globals,
rank=00 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=00 L14:     exec(code, run_globals)
rank=00 L15:   File "g2_metals.py", line 70, in <module>
rank=00 L16:     relax(slab)
rank=00 L17:   File "g2_metals.py", line 68, in relax
rank=00 L18:     dyn.run(fmax=fmax)
rank=00 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=00 L20:     return Dynamics.run(self)
rank=00 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=00 L22:     for converged in Dynamics.irun(self):
rank=00 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=00 L24:     self.atoms.get_forces()
rank=00 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=00 L26:     forces = self._calc.get_forces(self)
rank=00 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=00 L28:     return self.get_property('forces', atoms)
rank=00 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=00 L30:     self.calculate(atoms, [name], system_changes)
rank=00 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=00 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=00 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=00 L34:     self.initialize(atoms)
rank=00 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=00 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=00 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=00 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=00 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=00 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=00 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
GPAW CLEANUP (node 17): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=00 L42:     self.check_direction(gd, gd.pbc_c)
rank=00 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=00 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=00 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 0): <class 'ValueError'> occurred.  Calling MPI_Abort!
rank=29 L00: Traceback (most recent call last):
rank=29 L01:   File "/home/vazumah/anaconda3/envs/NAME/bin/gpaw", line 10, in <module>
rank=29 L02:     sys.exit(main())
rank=29 L03:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/main.py", line 76, in main
rank=29 L04:     ase_main('gpaw', 'GPAW command-line tool', __version__,
rank=29 L05:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/cli/main.py", line 103, in main
rank=29 L06:     f(args)
rank=29 L07:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/cli/python.py", line 36, in run
rank=29 L08:     runpy.run_path(args.arguments[0], run_name='__main__')
rank=29 L09:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 289, in run_path
rank=29 L10:     return _run_module_code(code, init_globals, run_name,
rank=29 L11:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 96, in _run_module_code
rank=29 L12:     _run_code(code, mod_globals, init_globals,
rank=29 L13:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/runpy.py", line 86, in _run_code
rank=29 L14:     exec(code, run_globals)
rank=29 L15:   File "g2_metals.py", line 70, in <module>
rank=29 L16:     relax(slab)
rank=29 L17:   File "g2_metals.py", line 68, in relax
rank=29 L18:     dyn.run(fmax=fmax)
rank=29 L19:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 269, in run
rank=29 L20:     return Dynamics.run(self)
rank=29 L21:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
rank=29 L22:     for converged in Dynamics.irun(self):
rank=29 L23:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
rank=29 L24:     self.atoms.get_forces()
rank=29 L25:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
rank=29 L26:     forces = self._calc.get_forces(self)
rank=29 L27:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
rank=29 L28:     return self.get_property('forces', atoms)
rank=29 L29:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
rank=29 L30:     self.calculate(atoms, [name], system_changes)
rank=29 L31:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 353, in calculate
rank=29 L32:     for _ in self.icalculate(atoms, properties, system_changes):
rank=29 L33:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 374, in icalculate
rank=29 L34:     self.initialize(atoms)
rank=29 L35:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 872, in initialize
rank=29 L36:     self.create_hamiltonian(realspace, mode, xc)
rank=29 L37:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/calculator.py", line 1108, in create_hamiltonian
rank=29 L38:     self.hamiltonian = RealSpaceHamiltonian(stencil=mode.interpolation,
rank=29 L39:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/hamiltonian.py", line 668, in __init__
rank=29 L40:     self.poisson.set_grid_descriptor(self.finegd)
rank=29 L41:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 38, in set_grid_descriptor
rank=29 L42:     self.check_direction(gd, gd.pbc_c)
rank=29 L43:   File "/home/vazumah/anaconda3/envs/NAME/lib/python3.10/site-packages/gpaw/dipole_correction.py", line 47, in check_direction
rank=29 L44:     raise ValueError('No axis perpendicular to {0}-plane!'
rank=29 L45: ValueError: No axis perpendicular to xy-plane!
GPAW CLEANUP (node 29): <class 'ValueError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 4 in communicator MPI_COMM_WORLD
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[d015:44256] 31 more processes have sent help message help-mpi-api.txt / mpi-abort
[d015:44256] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
